---
- name: Configure App
  hosts: reddit-app
  become: true

  vars:
    #db_host: 10.132.0.2
    db_host: 10.140.0.2
    #db_host: ${db_internal_ip}   
    #db_host: {{ hostvars['reddit-db'].address }}

  roles:
    - app

- name: Install nginx
  hosts: reddit-app
  become: true

  roles:
    - jdauphant.nginx

